/* tslint:disable:max-line-length */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/dashboard',
        parentId: 1,
        tag: 'dashboards'
    },
    {
        id: 'income',
        title: 'Income',
        parentId: 2,
        tag: 'incomes',
        type: 'collapsable',
        icon: 'heroicons_outline:currency-dollar',
        children: [
            {
                id: 'income.addIncome',
                title: 'Add Income',
                parentId: 2,
                type: 'basic',
                tag: 'addIncomes',
                link: '/income/add-income',
            },
            {
                id: 'income.manageIncome',
                title: 'Manage Income',
                tag: 'manageIncomes',
                parentId: 2,
                type: 'basic',
                link: '/income/manage-income',
            },
            {
                id: 'income.incomeCategories',
                title: 'Income Categories',
                tag: 'incomeCategories',
                parentId: 2,
                type: 'basic',
                link: '/income/income-categories',
            },
        ],
    },
    {
        id: 'expense',
        title: 'Expense',
        parentId: 3,
        tag: 'addExpenses',
        type: 'collapsable',
        icon: 'mat_outline:account_balance_wallet',
        children: [
            {
                id: 'expense.addExpense',
                title: 'Add Expense',
                tag: 'addExpenses',
                parentId: 3,
                type: 'basic',
                link: '/expense/add-expense',
            },
            {
                id: 'expense.manageExpense',
                title: 'Manage Expense',
                tag: 'manageExpenses',
                parentId: 3,
                type: 'basic',
                link: '/expense/manage-expense',
            },
            {
                id: 'expense.expenseCategories',
                title: 'Expense Categories',
                parentId: 3,
                type: 'basic',
                tag: 'expenseCategories',
                link: '/expense/expense-categories',
            },
        ],
    },
    {
        id: 'accounts',
        parentId: 4,
        title: 'Accounts',
        tag: 'accounts',
        type: 'collapsable',
        icon: 'mat_outline:account_box',
        children: [
            {
                id: 'accounts.newAccount',
                title: 'New Account',
                parentId: 4,
                tag: 'addAccounts',
                type: 'basic',
                link: '/accounts/new-account',
            },
            {
                id: 'accounts.manageAccount',
                title: 'Manage Accounts',
                parentId: 4,
                tag: 'manageAccounts',
                type: 'basic',
                link: '/accounts/manage-account',
            },
            {
                id: 'accounts.transactions',
                parentId: 4,
                title: 'Transactions',
                tag: 'transaction',
                type: 'basic',
                link: '/accounts/transactions',
            },
            {
                id: 'accounts.profitAndLoss',
                parentId: 4,
                title: 'Profit and Loss',
                tag: 'profitAndLoss',
                type: 'basic',
                link: '/accounts/profit-and-loss',
            },
        ],
    },
    {
        id: 'tax',
        title: 'Tax',
        parentId: 5,
        tag: 'taxes',
        type: 'collapsable',
        icon: 'heroicons_outline:receipt-tax',
        children: [
            {
                id: 'tax.addTax',
                title: 'Add Tax',
                type: 'basic',
                parentId: 5,
                tag: 'addTax',
                link: '/tax/add-tax',
            },
            {
                id: 'tax.manageTax',
                title: 'Manage Tax',
                tag: 'manageTax',
                parentId: 5,
                type: 'basic',
                link: '/tax/manage-tax',
            },
            {
                id: 'tax.taxStatement',
                title: 'Tax Statement',
                tag: 'taxStatements',
                parentId: 5,
                type: 'basic',
                link: '/tax/tax-statement',
            },
        ],
    },
    {
        id: 'reports',
        title: 'Reports',
        parentId: 6,
        tag: 'reports',
        type: 'collapsable',
        icon: 'heroicons_outline:document-text',
        children: [
            {
                id: 'reports.incomeReport',
                title: 'Income Report',
                parentId: 6,
                tag: 'incomeReports',
                type: 'basic',
                link: '/reports/income-report',
            },
            {
                id: 'reports.expenseReport',
                title: 'Expense Report',
                parentId: 6,
                tag: 'expenseReports',
                type: 'basic',
                link: '/reports/expense-report',
            },
            {
                id: 'reports.taxReport',
                title: 'Tax Report',
                parentId: 6,
                tag: 'taxReports',
                type: 'basic',
                link: '/reports/tax-report',
            },
            {
                id: 'reports.accountsStatement',
                title: 'Accounts Statement',
                parentId: 6,
                tag: 'accountsStatement',
                type: 'basic',
                link: '/reports/accounts-statement',
            },
        ],
    },
    {
        id: 'roles-and-permissions',
        title: 'Roles and Permissions',
        parentId: 7,
        type: 'collapsable',
        tag: 'rolesAndPermissions',
        icon: 'feather:user',
        children: [
            {
                id: 'roles-and-permissions.newUser',
                title: 'New User',
                tag: 'newUsers',
                parentId: 7,
                type: 'basic',
                link: '/roles-and-permissions/new-user',
            },
            {
                id: 'roles-and-permissions.manageUser',
                title: 'Manage User',
                tag: 'manageUsers',
                parentId: 7,
                type: 'basic',
                link: '/roles-and-permissions/manage-user',
            },
            {
                id: 'roles-and-permissions.manage-roles',
                title: 'Manage Roles',
                tag: 'manageRoles',
                parentId: 7,
                type: 'basic',
                link: '/roles-and-permissions/manage-roles',
            },
        ],
    },
    // {
    //     id: 'log',
    //     title: 'System Log',
    //     type: 'basic',
    //     icon: 'heroicons_outline:document-report',
    //     link: '/log',
    // },
    //
];
// export const compactNavigation: FuseNavigationItem[] = [
//     {
//         id: 'example',
//         title: 'Example',
//         type: 'basic',
//         icon: 'heroicons_outline:chart-pie',
//         link: '/example',
//     },
// ];
// export const futuristicNavigation: FuseNavigationItem[] = [
//     {
//         id: 'example',
//         title: 'Example',
//         type: 'basic',
//         icon: 'heroicons_outline:chart-pie',
//         link: '/example',
//     },
// ];
// export const horizontalNavigation: FuseNavigationItem[] = [
//     {
//         id: 'example',
//         title: 'Example',
//         type: 'basic',
//         icon: 'heroicons_outline:chart-pie',
//         link: '/example',
//     },
// ];
